### ISSUE TITLE
Release it

### ISSUE THREAD

**Issue by hawesie** [strands-project/soma#22]

**Comment by marc-hanheide** [comment]
@kunzel @cburbridge @hawesie 

I carried out the necessary steps to release a first version:
1. created release repo in https://github.com/strands-project-releases/soma
2. created CHANGELOGs (`catkin_generate_changelog -a`)
3. prepared a first version (`catkin_prepare_release`)
4. create a release track with bloom (`bloom-release -t indigo -n -r indigo soma`)

Let's see if this builds... Once https://github.com/strands-project/rosdistro/pull/608 is merged it will start building, so be prepared to receive emails ;-) 

But in any case, you can from now on use the "normal" method for releases.

**Comment by marc-hanheide** [comment]
@kunzel some `package.xml` have invalid email addresses, such as `lars@todo.todo`, please fix to receive build notifications.

**Comment by marc-hanheide** [comment]
BTW: The release worked! But #23 should be addressed.
