### ISSUE TITLE
Dependency on semantic_segmentation

### ISSUE THREAD

**Issue by hawesie** [strands-project/soma#33]
Is the dependency on semantic_segmentation simply on the service definitions? If so, we might want to separate them out if that package turns out to be unreleasable (https://github.com/strands-project/semantic_segmentation/issues/6).

**Comment by kunzel** [comment]
Yes, it just depends on the service definition. Should we simply exclude it from the package.xml so that people can get it without the need of semantic_segmentaiton?

**Comment by marc-hanheide** [comment]
No, please then separate out into some public `semantic_segmentation_msgs` package. Or get the relevant people to make it public ;-)
