### ISSUE TITLE
Little bug on update branch with map manager

### ISSUE THREAD

**Issue by jayyoung** [strands-project/soma#63]
One for @hkaraoguz  I think! seems like just a tiny logic error somewhere. I ran:

```
jxy@DOPPLEGANGER:~/soma_ws$` roslaunch soma_manager soma2_local.launch map_name:=aloof
```

Then I got

```
[ INFO] [1476960944.631418854]: Waiting for SOMA Map Service...
[INFO] [WallTime: 1476960944.684978] Running SOMA map manager
No maps are found in DB. Listening map_server for a map...
Map is received. Please enter a name for storing it in the database: [INFO] [WallTime: 1476960944.824152] Running SOMA data manager (dbname: soma2data, collection_name: soma2)
Waiting for the map info from soma_map_manager
[ERROR] [WallTime: 1476960949.942048] No 'soma/map_info' service, Quitting...
[soma_data_manager_node-2] process has finished cleanly
log file: /home/jxy/.ros/log/2d2d8b4c-96b3-11e6-9c5f-1c872c60d569/soma_data_manager_node-2*.log
```

But it was still listening for input from line 4 there, it seems... So I typed the name of my map

```
aloof
you entered aloof
map is now being published on soma/map topic
[ INFO] [1476960968.022460250]: Received map info. Map Name: aloof, Map Unique ID: 5808a2c70b226751c422fc71
[ INFO] [1476960968.022917305]: SOMA Query Service Ready.
```

Which worked, and then I ran the launch file again and everything was fine and it all worked. It looks like the system should be waiting after it asks for the map name, but it doesn't, and then just runs on looking for the soma/map_info topic, can't find it (because that doesn't come up until you give it the map name, I guess?) then crashes. The map was actually already in the db, I think, which is why I passed it as a parameter, but I guess it wasn't found for some reason? It might be because I created the map under the previous branch, which had lots of stuff named with "soma2", so could just be an issue with collection names.

**Comment by hkaraoguz** [comment]
Yes this is a logic error. I will increase the timeout limits for the nodes which I think will solve this problem.

**Comment by hkaraoguz** [comment]
@jayyoung I increased the wait timeouts. I think this issue is now solved with the latest commit.

**Comment by jayyoung** [comment]
Yep seems fixed to me!
