### ISSUE TITLE
soma roi manager visualises all configs. 

### ISSUE THREAD

**Issue by PDuckworth** [strands-project/soma#65]
@hkaraoguz @kunzel  
Shouldn't the ROI manager only visualise the config requested? It's messy whilst there are so many different ROI configs.

**Comment by hkaraoguz** [comment]
@PDuckworth Which version are you using? The version in the update branch uses the config info to visualize the ROIs.

**Comment by PDuckworth** [comment]
ah cool. I'll pull and test this tomorrow. 
Thanks

**Comment by hkaraoguz** [comment]
@PDuckworth Any news on this issue?

**Comment by PDuckworth** [comment]
Yes - this works with the update branch - Thanks!
