### ISSUE TITLE
Error in RVIZ

### ISSUE THREAD

**Issue by ferdianjovan** [strands-project/soma#7]
There is an error when running both soma_manager and soma_roi in RVIZ.
It says

```
Error getting time of latest transform between /map and map: (error code: 1)
```

Usually, running mongodb and map_server is enough to make soma and soma_roi run properly.
@PDuckworth encounters the same problem.
Any idea why?

**Comment by PDuckworth** [comment]
Agreed. I just run roscore, mongodb, map_server and soma_manager. Same error.

**Comment by kunzel** [comment]
@ferdianjovan your error message told you what was wrong ;)

**Comment by ferdianjovan** [comment]
I could fix that by adding tf transform from map to any name. But It was never happening before until recently.
So, I wondered whether others have the same issue.
Anyway, you could solve this by adding

```
rosrun tf static_transform_publisher 0.0 0.0 0.0 0.0 0.0 0.0 map [any_name_map] 100
```
