### ISSUE TITLE
SOMa Query (Service) - use the latest ROI 

### ISSUE THREAD

**Issue by kunzel** [strands-project/soma#72]
When querying objects within one particular ROI and no time is used, the latest region should be used. It seems as if the first version of a ROI is always used.
@hkaraoguz can you please check?

**Comment by hkaraoguz** [comment]
@kunzel According to my tests, It returns all the snapshots of the particular ROI. The latest should be the last element of the array

**Comment by kunzel** [comment]
Do you mean the ROI query service? Sorry, maybe this wasn't clear from by description but I was talking about object query (/soma/query_objects) where you ask for all objects within a ROI. However, if this region has a history, I believe the geo-spatial reasoning is carried out on the first instance of this ROI. But I think is would be sensible to use the most recent version...

**Comment by hkaraoguz** [comment]
@kunzel This should be fixed with the latest update. Can you please check?

**Comment by hkaraoguz** [comment]
@kunzel I am closing this issue if it is tested and working
