### ISSUE TITLE
Should the update branch be release as the new package?

### ISSUE THREAD

**Issue by nilsbore** [strands-project/soma#73]
It seems the new changes in the update branch are not released yet. Maybe it would be good to release it so that we have a solid interface to work against for the future? It seems quite some stuff has changed. Needed e.g. for https://github.com/strands-project/strands_3d_mapping/pull/111 to be merged.

**Comment by jayyoung** [comment]
Yep, that's the plan. We're discussing the required changes here: https://github.com/strands-project/soma/issues/68

I guess we should aim to do this by the end of the week at the latest so as to not hamper any more deployment prep.

**Comment by nilsbore** [comment]
Ok, so this seems to be fixed, cheers!
