### ISSUE TITLE
when does this update mongodb?

### ISSUE THREAD

**Issue by PDuckworth** [strands-project/soma#8]
@kunzel When does the soma manager update mongodb?

I deleted an object in rviz, and it was removed from the mongodb soma message store. But it remained in the geospatial message store. This caused me an issue because I obtain the objects from geo store, and the x, y coordinates from the message store.

**Comment by kunzel** [comment]
Hmm, I guess it should be deleted immediately when it is also removed in the message store. 
Did it happen for an object? for a ROI? or a point in a ROI? I'll try to reproduce it.

**Comment by PDuckworth** [comment]
an object.

**Comment by PDuckworth** [comment]
There was also strange behaviour, when I deleted one object multiple were removed (but not always).

I managed to make this arrangement, but needed to compare to msg and geo store to confirm.

![screenshot from 2015-04-17 13 51 58](https://cloud.githubusercontent.com/assets/5286841/7206317/ee92f4fa-e527-11e4-9e50-bd306fc6f4db.png)

**Comment by kunzel** [comment]
You mean, when you rightclick on an object to remove it several got removed (visually)? Or only in the geostore?

**Comment by PDuckworth** [comment]
visually. I didnt check in the stores.

**Comment by kunzel** [comment]
I've just tested adding and removing objects. It seems to work (message_store, geospatial_store). Maybe some ROS communication problem?

I've never seen that multiple objects are removed at the same time. Then they must have the same ID? Could you check whether this is true in your message_store? Objects were only inserted using RVIZ, right? Or also by other means?

**Comment by PDuckworth** [comment]
Only inserted using rviz. I will have a bit of a play next week to see if I can re-create the strange behaviour. It's not a huge problem if it's not likely to happen. (But if it does happen at g4s, my learning will not work).

**Comment by kunzel** [comment]
I think once the objects are in, they will not changed anymore during the deployment. So, if it works once it should work the whole time.

**Comment by kunzel** [comment]
@PDuckworth let me know if there is still a problem. But otherwise I think the issue can  be closed (but I don't have the rights)
